services:
  - type: web
    name: ms-pix-inteligente-py
    runtime: docker
    region: ohio
    
    # Variáveis de ambiente que você precisa configurar no painel do Render
    envVars:
      - key: SHEETS_CREDENTIALS_PATH
        scope: run
        sync: false

    # Comando customizado (opcional - Docker já tem CMD definido)
    # dockerCommand: uvicorn Controller.controlador:app --host 0.0.0.0 --port 10000
